### ISSUE TITLE
size mismatch problem during rendering process

### ISSUE THREAD

**Issue by HsiehTPE** [CUHK-AIM-Group/LGS#8]
Dear dev,

I encountered a problem while using the trained LGS model to render images. During the loading of the model weights, size mismatch errors between the parameters of the trained model and those in the current model. 

Here is the error traceback I received:

> Traceback (most recent call last):
>   File "render.py", line 183, in <module>
>     args.skip_train, args.skip_test, args.skip_video, args.new_max_sh, args
>   File "render.py", line 109, in render_sets
>     scene = Scene(dataset, gaussians, load_iteration=iteration, shuffle=False)
>   File "/root/autodl-tmp/LGS/scene/__init__.py", line 87, in __init__
>     "iteration_" + str(self.loaded_iter),
>   File "/root/autodl-tmp/LGS/scene/gaussian_model.py", line 273, in load_model
>     self._deformation.load_state_dict(weight_dict)
>   File "/root/miniconda3/envs/lgs/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1672, in load_state_dict
>     self.__class__.__name__, "\n\t".join(error_msgs)))
> RuntimeError: Error(s) in loading state_dict for deform_network:
>         size mismatch for deformation_net.grid.grids.0.0: copying a param with shape torch.Size([1, 64, 16, 16]) from checkpoint, the shape in current model is torch.Size([1, 64, 64, 64]).
>         size mismatch for deformation_net.grid.grids.0.1: copying a param with shape torch.Size([1, 64, 16, 16]) from checkpoint, the shape in current model is torch.Size([1, 64, 64, 64]).
>         size mismatch for deformation_net.grid.grids.0.2: copying a param with shape torch.Size([1, 64, 25, 16]) from checkpoint, the shape in current model is torch.Size([1, 64, 100, 64]).
> ......

This looks similar to the issue [size mismatch problem](https://github.com/CUHK-AIM-Group/LGS/issues/6#top)#6 , but this occurs in the rendering process.  How can I resolve this issue to successfully load and utilize the trained models?  As a reference, I have succesfully finished the training process to get the **LGS** model. And I saved the **EndoGaussian** model and its checkpoints as following code:

```
            # Ensuring model has same pattern with checkpoint in LGS
            if (iteration == 3000):
                print("\n[ITER {}] Saving Gaussians for LGS".format(iteration))
                scene.save("lgs_deformation_model", stage)

            if (iteration in checkpoint_iterations):
                print("\n[ITER {}] Saving Checkpoint".format(iteration))
                torch.save((gaussians.capture(), iteration), scene.model_path + "/chkpnt" + str(iteration) + ".pth")
```

Thanks for your patience and reading!

**Comment by LiuHengyu321** [comment]
Thank you for your interest in LGS! I will review the code and address the size mismatch issue that occurs during both the training and rendering processes before the conference begins.

**Comment by LiuHengyu321** [comment]
Hi @HsiehTPE,

Thank you for your patience while waiting for my response! I reviewed the code and discovered that I had lost the `--prune_deform` in the script for rendering, which is necessary for aligning the parameters of the deformation field. I've updated the repository to include this option. Thank you again for your reminder!
